### ISSUE TITLE
ngultra test

### ISSUE THREAD

**Issue by LeFl0w** [viveris/LoCod#2]
Hi,
trying to test locod on ngultra, I got the following error:
```
 $ ./locod.sh -t ngultra -f demo/example_readme/main.c 
Checking dependecies ...

********************************************************************************
                    ____                  _
                   | __ )  __ _ _ __ ___ | |_   _   _
                   |  _ \ / _` | '_ ` _ \| '_ \| | | |
                   | |_) | (_| | | | | | | |_) | |_| |
                   |____/ \__,_|_| |_| |_|_.__/ \__,_|

********************************************************************************
                         High-Level Synthesis Tool

                         Politecnico di Milano - DEIB
                          System Architectures Group
********************************************************************************
                Copyright (C) 2004-2022 Politecnico di Milano
  Version: PandA 0.9.8 - Revision eda4c22d5adaec44fd8489ae49b854b244d2cf70-HEAD

- Panda docker found
Compiling C code ... make: *** No targets specified and no makefile found.  Stop.
```
dependencies check is correct (I only installed :  docker sdk-ngultra ,panda-bambu and fpga-tb)

 Am I missing something?
thanks.
Florent

**Comment by Twistix** [comment]
Hi Florent,

I don't realy understand why there is this error when building executable for the NG-Ultra. It seems that the docker NG-Ultra BSP is found but the ngultra_bsp inside is missing.
I made some modifications on the [ngutra SDK docker submodule](https://github.com/viveris/LoCod-docker-sdk-ngultra/tree/056fe905d0e5960c56db638c572c4a4f9b9e3fc3), and also in the locod.sh script (the dependencies check at the start were not working).

Could you please try to re-build the NG-Ultra SDK docker with the new version. You need 2 variables $NX_USERNAME and $NX_PERSONAL_ACCESS_TOKEN which are credentials to pull on the NanoXplore Github. Then you can run the following command inside the NG-Ultra SDK submodule folder :
```console
docker build -t ${IMG_NAME} --build-arg NX_USERNAME=${NX_USERNAME} --build-arg NX_PERSONAL_ACCESS_TOKEN=${NX_PERSONAL_ACCESS_TOKEN} -f Dockerfile .
```
(all the steps to build the image are now explained in the README of the submodule)

Then you can change the **NG_ULTRA_SDK_DOCKER_IMG** (line 49) in [locod.sh](https://github.com/viveris/LoCod/blob/master/locod.sh) to the image name you choose for the NG-Ultra SDK docker image, and you can retry the build :
```console
./locod.sh -t ngultra -f demo/example_readme/main.c 
```

I tested it on my side, it worked. Let me know if it works for you or if you have any other errors.

Best regards,
Julien

**Comment by LeFl0w** [comment]
I thanks it is better, but still blocked.
```
                          System Architectures Group
********************************************************************************
                Copyright (C) 2004-2022 Politecnico di Milano
  Version: PandA 0.9.8 - Revision eda4c22d5adaec44fd8489ae49b854b244d2cf70-HEAD

- Panda docker found
arm-none-eabi-gcc (GNU Arm Embedded Toolchain 10.3-2021.10) 10.3.1 20210824 (release)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

- ngultra SDK docker found
Unable to find image 'nx-tools:2.1' locally
docker: Error response from daemon: pull access denied for nx-tools, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
- NX docker not found
flo@Albertine ~/FLORENT/GIT/LoCod (master) $ ./locod.sh -t ngultra -f demo/example_readme//main.c 
```

I think it miss docker nx-tools receipe

**Comment by LeFl0w** [comment]
by changing the default docker image name from nx-tools to nanoxplore it worked.
It goes in a way of issue #1 . If there was a shell script to generate all the docker image with the right tag it will avoid this type of error.
thanks
